export const blocksData = [
  {
    id: "Block-1",
    column: 1,
    row: 1,
    width: 24,
    blockWidth: "w-24",
    bgColor: "bg-sky-400",
    border: "border-sky-600",
    level: "easy",
  },
  {
    id: "Block-2",
    column: 1,
    row: 2,
    width: 32,
    blockWidth: "w-32",
    bgColor: "bg-violet-400",
    border: "border-violet-600",
    level: "easy",
  },
  {
    id: "Block-3",
    column: 1,
    row: 3,
    width: 40,
    blockWidth: "w-40",

    bgColor: "bg-green-400",
    border: "border-green-600",
    level: "easy",
  },
  {
    id: "Block-4",
    column: 1,
    row: 4,
    width: 48,
    blockWidth: "w-48",

    bgColor: "bg-yellow-400",

    border: "border-yellow-600",
    level: "medium",
  },
  {
    id: "Block-5",
    column: 1,
    row: 5,
    width: 64,
    blockWidth: "w-64",

    bgColor: "bg-red-400",
    border: "border-red-600",
    level: "hard",
  },
  {
    id: "Block-6",
    column: 1,
    row: 6,
    width: 80,
    blockWidth: "w-80",
    bgColor: "bg-fuchsia-400",
    border: "border-fuchsia-600",
    level: "hard",
  },
];
